name: A workflow for my Hello World file
on: push

jobs:
build:
name: Hello world action
runs-on: ubuntu-latest
steps:
- name: build
working-directory: initial
run: gradle clean build
pipeline-scan:
runs-on: ubuntu-latest
steps:
- name: Set up JDK 1.8
uses: actions/setup-java@v1
with:
java-version: 1.8
- name: Download the Pipeline Scanner
uses: wei/curl@master
with:
args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
- name: Unzip the Pipeline Scanner
run: unzip pipeline-scan-LATEST.zip
steps:
- name: Intro
- uses: actions/checkout@v1
- uses: ./action-a
with:
MY_NAME: "zzVeracode"
